//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExampleDBFirst.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookStorage
    {
        public int BookId { get; set; }
        [Required(ErrorMessage = "Empty name")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Invalid name length")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Empty autor")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Invalid autor length")]
        public string Author { get; set; }
    
        public virtual BookVisits BookVisits { get; set; }
    }
}