//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExampleDBFirst.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookVisits
    {
        public int BookId { get; set; }
        public int Visit { get; set; }
    
        public virtual BookStorage BookStorage { get; set; }
    }
}
